name: timelines
version: 0.2.1
description: A powerful & easy to use timeline package for Flutter. All UI components in this package are separate widgets.
homepage: https://github.com/gangsterpp/timelines
repository: https://github.com/gangsterpp/timelines
issue_tracker: https://github.com/gangsterpp/timelines/issues

environment:
  sdk: '>=2.14.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: 5.1.1

flutter: 
